version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.0
    volumes:
      - ./data:/data/db
      - ./scripts:/app/scripts
    ports:
      - "27017:27017"
